name: scrapi

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "10700:10700"
    env_file:
      - .env
      - .env.development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10700/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
