services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "10700:10700"
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.development
    restart: unless-stopped
