services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10700:10700"
    volumes:
      - .:/app
    env_file:
      - .env
      - .env.development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10700", "--reload"]
    restart: unless-stopped
