"""Network-level ad/tracker blocker for the cloak provider.

Emulates the network-blocking half of uBlock (the half that matters for
HTML extraction) using Playwright's `page.route()`.

Two-tier matching, both at module import:

1. **Bundled host denylist** at `/opt/adblock_hosts.txt` — generated by
   the Dockerfile from a pinned StevenBlack/hosts release (~80K hosts,
   ads + malware + fakenews). Lookup is subdomain-chain: a hit on a
   parent domain blocks every subdomain.
2. **Legacy hardcoded fallback** — ~50 high-signal hosts, always unioned
   in. Plus a tiny path-pattern set for non-host stragglers like
   `yandex.ru/metrika`.
"""

from __future__ import annotations

import logging
from pathlib import Path
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# Non-host patterns. Anything path-y, regex-y, or sub-host-y goes here.
# Substring-matched against the full URL. Keep small.
_PATTERN_DENYLIST: frozenset[str] = frozenset(
    [
        "yandex.ru/metrika",
    ]
)


_LEGACY_HOST_DENYLIST: frozenset[str] = frozenset(
    [
        "doubleclick.net",
        "googletagmanager.com",
        "google-analytics.com",
        "googletagservices.com",
        "googlesyndication.com",
        "googleadservices.com",
        "adservice.google.com",
        "facebook.net",
        "connect.facebook.net",
        "amazon-adsystem.com",
        "ads-twitter.com",
        "static.ads-twitter.com",
        "bat.bing.com",
        "clarity.ms",
        "adnxs.com",
        "criteo.com",
        "criteo.net",
        "openx.net",
        "rubiconproject.com",
        "pubmatic.com",
        "casalemedia.com",
        "scorecardresearch.com",
        "quantserve.com",
        "moatads.com",
        "outbrain.com",
        "taboola.com",
        "mc.yandex.ru",
        "segment.com",
        "segment.io",
        "hotjar.com",
        "mixpanel.com",
        "amplitude.com",
        "fullstory.com",
        "logrocket.com",
        "mouseflow.com",
        "luckyorange.com",
        "crazyegg.com",
        "newrelic.com",
        "datadoghq-browser-agent.com",
        "onetrust.com",
        "cookiebot.com",
        "consensu.org",
        "branch.io",
        "appsflyer.com",
        "kissmetrics.com",
        "intercomcdn.com",
        "drift.com",
    ]
)


_HOSTS_FILE = Path("/opt/adblock_hosts.txt")


def _load_bundled_hosts() -> frozenset[str]:
    """Read the build-time-generated host list. Empty set if missing."""
    try:
        text = _HOSTS_FILE.read_text(encoding="utf-8")
    except (FileNotFoundError, PermissionError) as exc:
        logger.warning(
            "Adblock hosts file %s not available (%s); falling back to legacy %d-host list",
            _HOSTS_FILE,
            exc.__class__.__name__,
            len(_LEGACY_HOST_DENYLIST),
        )
        return frozenset()
    hosts = frozenset(line.strip().lower() for line in text.splitlines() if line.strip() and not line.startswith("#"))
    logger.info("Loaded %d adblock hosts from %s", len(hosts), _HOSTS_FILE)
    return hosts


# Active denylist: the union of the bundled file and the legacy core.
# StevenBlack deliberately excludes some contentious hosts (Facebook,
# certain CDNs) to avoid breaking login flows; our legacy list keeps
# them in. Unioning gives the broadest coverage without losing either.
BLOCKED_HOSTS: frozenset[str] = _load_bundled_hosts() | _LEGACY_HOST_DENYLIST


def is_blocked(url: str) -> bool:
    """Return True if the URL should be aborted.

    Subdomain-chain match against the host denylist: `ads.foo.bar.com`
    checks `ads.foo.bar.com`, then `foo.bar.com`, then `bar.com`, then
    `com`. A hit on any of those returns True. This means listing a
    tracker's base domain (e.g. `doubleclick.net`) blocks every
    subdomain automatically.

    Pattern denylist is substring-matched against the whole URL; covers
    non-host needs (path-anchored rules).
    """
    if any(p in url for p in _PATTERN_DENYLIST):
        return True
    host = (urlparse(url).hostname or "").lower()
    while host:
        if host in BLOCKED_HOSTS:
            return True
        _, _, host = host.partition(".")
    return False


def block_ads(route) -> None:
    """Playwright route handler. Abort blocked requests, let others through.

    Wire with `page.route("**/*", block_ads)` BEFORE navigation. The
    handler stays subscribed for the lifetime of the page.
    """
    if is_blocked(route.request.url):
        route.abort()
    else:
        route.continue_()
