import os

API_TOKEN = os.environ["SCRAPI_API_TOKEN"]
FETCH_TIMEOUT_MS = int(os.environ.get("SCRAPI_FETCH_TIMEOUT_MS", "30000"))

SCRAPLING_TIMEOUT_MS = 15000

FIRECRAWL_API_KEY = os.environ.get("FIRECRAWL_API_KEY", "")
FIRECRAWL_BASE_URL = "https://api.firecrawl.dev/v1"
FIRECRAWL_TIMEOUT_SECONDS = 30

CLOUDFLARE_API_KEY = os.environ.get("CLOUDFLARE_API_KEY", "")
CLOUDFLARE_ACCOUNT_ID = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "")
CLOUDFLARE_TIMEOUT_SECONDS = 30
